apiVersion: v2
name: drupal
version: 1.8.0
dependencies:
- name: mariadb
  version: 7.5.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: mariadb.enabled,drupal.mariadb.enabled,global.mariadb.enabled
- name: pxc-db
  version: 1.12.x
  repository: https://percona.github.io/percona-helm-charts/
  condition: pxc-db.enabled
- name: memcached
  version: 4.2.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: memcached.enabled
- name: redis
  version: 16.13.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: mailhog
  version: 5.1.x
  repository: https://codecentric.github.io/helm-charts
  condition: mailhog.enabled
- name: elasticsearch
  version: 8.5.x
  # repository: https://helm.elastic.co
  # Forked at https://github.com/elastic/helm-charts/commit/2fd64d0af65f14df7aa01da591919460dabac4b3
  repository: file://../elasticsearch
  condition: elasticsearch.enabled
- name: silta-release
  version: ^1.x
  repository: file://../silta-release
