dependencies:
- name: mariadb
  version: 4.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled,drupal.mariadb.enabled,global.mariadb.enabled
- name: memcached
  version: 2.3.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: memcached.enabled
- name: mailhog
  version: 3.0.1
  repository: https://codecentric.github.io/helm-charts
  condition: mailhog.enabled
- name: elasticsearch
  version: 7.3.x
# Use our fork of the helm chart until https://github.com/elastic/helm-charts/pull/298 is merged.
# repository: https://helm.elastic.co
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: elasticsearch.enabled
