# Adds cluster admin role to the Kyverno background controller service account (remove after policy creation)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:generate-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
---
# Runs once, adds PSA labels to existing namespaces
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-psa-labels-existing-ns
  annotations:
    policies.kyverno.io/title: Add PSA Label to Existing Namespaces
    policies.kyverno.io/category: Pod Security Admission
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Namespace
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/description: >-
      Adds PSA labels to existing namespaces.
spec:
  mutateExistingOnPolicyUpdate: true
  background: false
  rules:
  - name: label-privileged-namespaces
    match:
      any:
      - resources:
          kinds:
          - Namespace
    mutate:
      targets:
        - apiVersion: v1
          kind: Namespace
      patchStrategicMerge:
        metadata:
          labels:
            +(pod-security.kubernetes.io/enforce): baseline
            +(pod-security.kubernetes.io/enforce-version): latest
            +(pod-security.kubernetes.io/warn): baseline
            +(pod-security.kubernetes.io/warn-version): latest