apiVersion: v1
name: frontend
version: 0.2.40
apiVersion: v2
dependencies:
- name: mariadb
  version: 7.10.x
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
- name: elasticsearch
  version: 7.4.1
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: rabbitmq
  version: 6.17.x
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
- name: silta-release
  version: 0.1.1
  repository: file://../silta-release

