apiVersion: v2
name: frontend
version: 1.14.1
dependencies:
- name: mariadb
  version: 7.10.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: mariadb.enabled
- name: mailhog
  version: 5.1.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: mailhog.enabled
- name: mailpit
  version: 0.24.x
  repository: https://jouve.github.io/charts/
  condition: mailpit.enabled
- name: elasticsearch
  version: 8.5.x
  # repository: https://helm.elastic.co
  # Forked at https://github.com/elastic/helm-charts/commit/2fd64d0af65f14df7aa01da591919460dabac4b3
  repository: file://../elasticsearch
  condition: elasticsearch.enabled
- name: rabbitmq
  version: 6.17.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: rabbitmq.enabled
- name: mongodb
  version: 14.12.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: mongodb.enabled
- name: postgresql
  version: 13.2.x
  # repository: https://charts.bitnami.com/bitnami
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: postgresql.enabled
- name: silta-release
  version: ^1.x
  repository: file://../silta-release
- name: redis
  version: 19.1.5
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
