apiVersion: v2
name: frontend
version: 0.2.83
dependencies:
- name: mariadb
  version: 7.10.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: mariadb.enabled
- name: elasticsearch
  version: 7.8.x
#  repository: https://helm.elastic.co
  repository: file://../elasticsearch
  condition: elasticsearch.enabled
- name: rabbitmq
  version: 6.17.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: rabbitmq.enabled
- name: mongodb
  version: 10.26.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: mongodb.enabled
- name: silta-release
  version: 0.1.1
  repository: file://../silta-release
