{{- if index (index .Values "silta-downscaler") "enabled" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-downscaler
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-downscaler
rules:
  - apiGroups: ["", "extensions", "networking.k8s.io", "batch", "apps"]
    resources: ["services", "services/status", "ingresses", "deployments", "deployments/status", "cronjobs", "statefulsets"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "create", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "patch", "create", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-downscaler
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-downscaler
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-downscaler
  apiGroup: rbac.authorization.k8s.io
{{- end }}
