apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: releases.silta.wdr.io
spec:
  group: silta.wdr.io
  scope: Namespaced
  names:
    kind: Release
    singular: release
    plural: releases
  versions:
  - name: v1
    served: true
    storage: true
    additionalPrinterColumns:
      - name: Release
        type: string
        description: Name of the release
        jsonPath: .spec.releaseName
      - name: Branch
        type: string
        description: Branch name of the release
        jsonPath: .spec.branchName
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
            type: object
            properties:
              branchName:
                type: string
              releaseName:
                type: string
