apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-splash
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 8080
  selector:
    name: {{ .Release.Name }}-splash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-splash
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-splash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-splash
    spec:
      enableServiceLinks: false
      containers:
      - image: "wunderio/silta-splash:v1"
        name: nginx
        resources:
          {{- .Values.splash.resources | toYaml | nindent 10 }}
