{{- if .Values.gitAuth.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jumpserver
  {{- if .Values.gitAuth.annotations }}
  annotations:
  {{- range $key, $value := .Values.gitAuth.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  ports:
    - name: ssh
      port: {{ .Values.gitAuth.port }}
  type: "LoadBalancer"
{{- if .Values.gitAuth.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gitAuth.loadBalancerIP }}
{{- end }}
{{- if .Values.gitAuth.allowedIps }}
  loadBalancerSourceRanges:
    {{- .Values.gitAuth.allowedIps | toYaml | nindent 2 -}}
{{- end }}
  selector:
    name: {{ .Release.Name }}-jumpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jumpserver
spec:
  replicas: {{ .Values.gitAuth.replicas }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-jumpserver
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-jumpserver
    spec:
      enableServiceLinks: false
      containers:
      - name: {{ .Release.Name }}-jumpserver
        image: wunderio/sshd-gitauth:v0.2
        imagePullPolicy: Always
        ports:
          - containerPort: 22
        env:
          - name: GITAUTH_URL
            value: {{ .Values.gitAuth.keyserver.url | default (printf "https://keys.%s/api/1/git-ssh-keys" .Values.clusterDomain) | quote }}
          - name: GITAUTH_USERNAME
            value: {{ .Values.gitAuth.keyserver.username | default .Values.sshKeyServer.apiUsername | quote }}
          - name: GITAUTH_PASSWORD
            value: {{ .Values.gitAuth.keyserver.password | default .Values.sshKeyServer.apiPassword | quote }}
          - name: GITAUTH_SCOPE
            value: {{ required "A valid .Values.gitAuth.scope entry required!" .Values.gitAuth.scope | quote }}
          - name: OUTSIDE_COLLABORATORS
            value: {{ .Values.gitAuth.outsideCollaborators | default true | quote }}
        volumeMounts:
        - name: shell-keys
          mountPath: /etc/ssh/keys
        resources:
          {{- .Values.gitAuth.resources | toYaml | nindent 10 }}
      volumes:
      - name: shell-keys
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-shell-keys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shell-keys
  labels:
    name: {{ .Release.Name }}-jumpserver
spec:
  {{- if .Values.gitAuth.persistence.storageClassName }}
  storageClassName: {{ .Values.gitAuth.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - {{ .Values.gitAuth.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.gitAuth.persistence.size }}
  selector:
    matchLabels:
      name: {{ $.Release.Name }}-shell-keys-pv
{{- end }}
# silta-shared volume definition if its storage is selected
{{- if .Values.gitAuth.persistence.storageClassName }}
{{- if eq .Values.gitAuth.persistence.storageClassName "silta-shared" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-shell-keys-pv
  labels:
    name: {{ $.Release.Name }}-shell-keys-pv
spec:
  accessModes:
    - {{ .Values.gitAuth.persistence.accessMode }}
  capacity:
    storage: {{ .Values.gitAuth.persistence.size }}
  storageClassName: {{ .Values.gitAuth.persistence.storageClassName }}
  {{- if .Values.gitAuth.persistence.csiDriverName }}
  csi:
    driver: {{ .Values.gitAuth.persistence.csiDriverName }}
    volumeHandle: {{ $.Release.Name }}-shell-keys-pv
    volumeAttributes:
      remotePathSuffix: /{{ $.Release.Namespace }}/jumpserver
      umask: "077"
  {{- end }}
{{- end }}
{{- end }}
