---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jumpserver
spec:
  ports:
    - name: ssh
      port: 22
  type: "LoadBalancer"
{{- if .Values.gitAuth.allowedIps }}
  loadBalancerSourceRanges:
    {{- .Values.gitAuth.allowedIps | toYaml | nindent 2 -}}
{{- end }}
  selector:
    name: {{ .Release.Name }}-jumpserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jumpserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-jumpserver
    spec:
      containers:
      - name: {{ .Release.Name }}-jumpserver
        image: wunderio/sshd-gitauth:v0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 22
        env:
          - name: GITAUTH_API_TOKEN
            value: {{ required "A valid .Values.gitAuth.apiToken entry required!" .Values.gitAuth.apiToken | quote }}
          - name: GITAUTH_HOST
            value: {{ required "A valid .Values.gitAuth.host entry required!" .Values.gitAuth.host | quote }}
          - name: GITAUTH_ORGANISATION
            value: {{ required "A valid .Values.gitAuth.organisation entry required!" .Values.gitAuth.organisation | quote }}
        volumeMounts:
        - name: shell-keys
          mountPath: /etc/ssh/keys
      volumes:
      - name: shell-keys
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-shell-keys
      resources:
        {{- .Values.gitAuth.resources | toYaml | nindent 8 }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shell-keys
  labels:
    name: {{ .Release.Name }}-jumpserver
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
