{{- if .Values.ssl.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls-cert-default
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-tls-cert-default
  duration: 100h # 90d
  renewBefore: 5h # 15d
  commonName: {{ .Values.clusterDomain }}
  dnsNames:
  - {{ .Values.clusterDomain }}
  issuerRef:
    name: selfsigned
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
{{- end }}
