apiVersion: v1
name: mariadb
version: 7.10.4
appVersion: 10.3.24
description: Fast, reliable, scalable, and easy to use open-source relational database system. MariaDB Server is intended for mission-critical, heavy-load production systems as well as for embedding into mass-deployed software. Highly available MariaDB cluster.
keywords:
  - mariadb
  - mysql
  - database
  - sql
  - prometheus
home: https://github.com/bitnami/charts/tree/master/bitnami/mariadb
icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
sources:
  - https://github.com/bitnami/bitnami-docker-mariadb
  - https://github.com/prometheus/mysqld_exporter
  - https://mariadb.org
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
annotations:
  category: Database
