apiVersion: v2
appVersion: "1.0"
description: Setup a silta kubernetes cluster.
name: silta-cluster
version: 1.6.2
# kubeVersion: '>=1.20.0-0'
dependencies:
- name: ingress-nginx
  # check kubernetes version requirements here: https://github.com/kubernetes/ingress-nginx
  version: 4.10.x
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress-nginx.enabled
- name: nginx-ingress
  # check kubernetes version requirements here: https://github.com/nginxinc/kubernetes-ingress/tree/057c6d7e4f2361f5d2ddd897e9995bcb48ed7e32#nginx-ingress-controller-releases
  version: 0.17.x
  repository: https://helm.nginx.com/stable
  condition: nginx-ingress.enabled
- name: traefik
  version: 1.87.x
  repository: file://../legacy_traefik
  condition: traefik.enabled
- name: ingress-nginx
  # check kubernetes version requirements here: https://github.com/kubernetes/ingress-nginx
  version: 4.10.x
  alias: nginx-traefik
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx-traefik.enabled
- name: pxc-operator
  version: 1.12.x
  repository: https://percona.github.io/percona-helm-charts/
  condition: pxc-operator.enabled
- name: minio
  version: 6.0.x
  # repository: https://helm.min.io/
  repository: file://../forked/minio/minio-6.0.5
  condition: minio.enabled
- name: csi-rclone
  version: 0.3.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: csi-rclone.enabled
- name: cert-manager
  version: 0.10.x
  repository: https://charts.jetstack.io/
  condition: cert-manager.enabled
- name: silta-proxy
  version: ^1.x
  repository: file://../silta-proxy
  condition: silta-proxy.enabled
- name: instana-agent
  version: 1.2.x
  repository: https://agents.instana.io/helm
  condition: instana-agent.enabled
- name: nfs-subdir-external-provisioner
  repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  version: 4.0.x
  condition: nfs-subdir-external-provisioner.enabled
- name: nfs-subdir-external-provisioner
  repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  version: 4.0.x
  alias: silta-shared-nfs
  condition: silta-shared-nfs.enabled
- name: docker-registry
  repository: https://helm.twun.io
  version: 2.1.x
  condition: docker-registry.enabled
