apiVersion: v2
appVersion: "1.0"
description: Setup a silta kubernetes cluster.
name: silta-cluster
version: 0.2.33
dependencies:
- name: traefik
  version: 1.87.x
  repository: file://../legacy_traefik
  condition: traefik.enabled
- name: redis
  version: 10.4.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: deploymentRemover.enabled
- name: pxc-operator
  version: 1.9.x
  repository: https://percona.github.io/percona-helm-charts/
  condition: pxc-operator.enabled
- name: minio
  version: 6.0.x
  repository: https://helm.min.io/
  condition: minio.enabled
- name: csi-rclone
  version: 0.2.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: csi-rclone.enabled
- name: cert-manager
  version: 0.10.x
  repository: https://charts.jetstack.io/
  condition: cert-manager.enabled
- name: silta-proxy
  version: 0.1.0
  repository: file://../silta-proxy
  condition: silta-proxy.enabled
- name: instana-agent
  version: 1.2.x
  repository: https://agents.instana.io/helm
  condition: instana-agent.enabled
- name: nfs-subdir-external-provisioner
  repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  version: 4.0.x
  condition: nfs-subdir-external-provisioner.enabled
- name: docker-registry
  repository: https://helm.twun.io
  version: 2.1.x
  condition: docker-registry.enabled
