kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-placeholder
spec:
  selector:
    matchLabels:
      app: downscaler-placeholder
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: downscaler-placeholder
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: downscaler
      containers:
        - name: placeholder
          image: wunderio/silta-downscaler
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PLACEHOLDER_DOMAIN
              value: {{ .Values.domain }}
            - name: PLACEHOLDER_SERVICE_NAME
              value: {{ .Release.Name }}-placeholder
            - name: PLACEHOLDER_SERVICE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-placeholder
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: downscaler-placeholder
    release: {{ .Release.Name }}
