apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-placeholder
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: "http,https"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-placeholder
          servicePort: 80
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
spec:
  secretName: {{ .Release.Name }}-tls
  dnsNames:
  - {{ .Values.domain }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingress: {{ .Release.Name }}-placeholder
        domains:
          - {{ .Values.domain }}