{{- if .Values.backup.enabled }}
{{- $db_password := randAlphaNum 20 }}
{{- $params := dict "db_password" $db_password  -}}
apiVersion: {{ include "drupal.cron.api-version" $ | trim }}
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
    cronjob-type: backup
    cronjob: "true"
spec:
  {{- if .Values.timezone }}
  {{- if eq ( include "drupal.cron.timezone-support" . ) "true" }}
  timeZone: {{ .Values.timezone | quote }}
  {{- end }}
  {{- end }}
  schedule: {{ .Values.backup.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      # This is a fallback for sidecar termination failure.
      # Six hours should be enough for backup/validation actions.
      activeDeadlineSeconds: 21600
      backoffLimit: 2
      template:
        metadata:
          annotations:
            nrmitchi.com/sidecars: mariadb
          labels:
            {{- include "drupal.release_labels" . | nindent 12 }}
            cronjob-type: backup
            cronjob: "true"
        spec:
          enableServiceLinks: false
          containers:
          - name: backup
            {{- include "drupal.php-container" . | nindent 12 }}
            volumeMounts:
              {{- include "drupal.volumeMounts" . | nindent 14 }}
              - name: {{ .Release.Name }}-backup
                mountPath: /backups
            command: ["/bin/bash", "-c"]
            args:
              - |
                {{ include "drupal.backup-command" (merge $params . ) | nindent 16 }}
                {{ include "mariadb.db-validation" (merge $params . ) | nindent 16 }}
          - name: mariadb
            image: docker.io/bitnami/mariadb:10.3.24-debian-10-r49
            imagePullPolicy: IfNotPresent
            env:
            - name: MARIADB_ROOT_PASSWORD
              value: {{ $db_password }}
            - name: MARIADB_DATABASE
              value: drupal
            ports:
            - containerPort: 3306
              name: mariadb
            resources:
              {{- .Values.backup.resources | toYaml | nindent 14 }}
          restartPolicy: Never
          volumes:
            {{- include "drupal.volumes" . | nindent 12 }}
            - name: {{ .Release.Name }}-backup
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-backup
          {{- include "drupal.imagePullSecrets" . | nindent 10 }}
{{- end }}

---
