apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-drupal
  annotations:
    auto-downscale/down: "false"
    {{- if eq .Values.cluster.type "gke" }}
    beta.cloud.google.com/backend-config: '{"ports": {"80":"{{ .Release.Name }}-drupal"}}'
    {{- end }}
    {{- if .Values.cluster }}
    {{- if .Values.cluster.vpcNative }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- end }}
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  type: NodePort
  # We explicitly unset this, in case the application is currently downscaled.
  externalName: null
  ports:
    - port: 80
  selector:
    {{- include "drupal.release_selector_labels" . | nindent 4 }}
    deployment: drupal
