{{- range $index, $job := .Values.php.cron }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  {{- $indexHash := sha256sum $index | trunc 3 }}
  name: {{ $.Release.Name }}-cron-{{ (gt (len $index) 6) | ternary ( print ($index | trunc 3) print $indexHash ) $index}}
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "drupal.release_labels" $ | nindent 12 }}
            cronjob: "true"
        spec:
          enableServiceLinks: false
          containers:
          - name: drupal-cron
            {{- include "drupal.php-container" $ | nindent 12 }}
            volumeMounts:
              {{- include "drupal.volumeMounts" $ | nindent 14 }}
            command: ["/bin/bash", "-c"]
            args:
              - |
                 set -ex
                 if [ ! {{ include "drupal.installation-in-progress-test" $ }} ]
                 then
                  {{ $job.command | nindent 18 }}
                 else
                   exit 1
                 fi
            resources:
              {{ if $job.resources }}
              {{- $job.resources | toYaml | nindent 14 }}
              {{ else }}
              {{- $.Values.php.resources | toYaml | nindent 14 }}
              {{- end }}
          restartPolicy: Never
          nodeSelector:
            {{ if $job.nodeSelector }}
            {{- $job.nodeSelector | toYaml | nindent 12 }}
            {{ else }}
            {{- $.Values.php.nodeSelector | toYaml | nindent 12 }}
            {{- end }}
          tolerations:
            {{ if $job.nodeSelector }}
            {{- include "drupal.tolerations" $job.nodeSelector | nindent 12 }}
            {{ else }}
            {{- include "drupal.tolerations" $.Values.php.nodeSelector | nindent 12 }}
            {{- end }}

          volumes:
            {{- include "drupal.volumes" $ | nindent 12 }}

          {{- include "drupal.imagePullSecrets" $ | nindent 10 }}
---
{{- end }}
