{{- range $index, $job := .Values.php.cron }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-cron-{{ $index }}
  labels:
    {{ include "drupal.release_labels" $ | indent 4 }}
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: Forbid
  backOffLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drupal-cron
            {{ include "drupal.php-container" $ | indent 12 }}
            command: ["/bin/sh", "-c"]
            args:
              - {{ $job.command | quote }}
            resources:
{{ $.Values.php.resources | toYaml | indent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{ include "drupal.volumes" $ | indent 12 }}

          {{ include "drupal.imagePullSecrets" $ | indent 10 }}
---
{{- end }}