{{- $context_ingress := .Values.ingress.default }}
{{- $context_ssl := .Values.ssl }}
{{- if $context_ingress.tls }}
{{- if has $context_ssl.issuer (list "letsencrypt" "letsencrypt-staging") }}
apiVersion: {{ include "cert-manager.api-version" . | trim }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
  annotations:
    cert-manager.io/issue-temporary-certificate: "true" 
    acme.cert-manager.io/http01-override-ingress-name: "{{ $.Release.Name }}-drupal"
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls
  dnsNames:
  - {{ include "drupal.domain" . | quote }}
  issuerRef:
    name: {{ $context_ssl.issuer }}
    kind: ClusterIssuer
{{- if eq ( include "cert-manager.api-version" . | trim ) "certmanager.k8s.io/v1alpha1" }}
  acme:
    config:
      - http01:
          ingress: {{ .Release.Name }}-drupal
        domains:
          - {{ template "drupal.domain" . }}
{{- end }}
---
{{- range $index, $prefix := .Values.domainPrefixes }}
apiVersion: {{ include "cert-manager.api-version" $ | trim }}
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-crt-p{{ $index }}
  annotations:
    cert-manager.io/issue-temporary-certificate: "true" 
    acme.cert-manager.io/http01-override-ingress-name: "{{ $.Release.Name }}-drupal"
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  secretName: {{ $.Release.Name }}-tls-p{{ $index }}
  dnsNames:
  - '{{$prefix}}.{{ include "drupal.domain" $ }}'
  issuerRef:
    name: {{ $context_ssl.issuer }}
    kind: ClusterIssuer
{{- if eq ( include "cert-manager.api-version" $ | trim ) "certmanager.k8s.io/v1alpha1" }}
  acme:
    config:
      - http01:
          ingress: {{ $.Release.Name }}-drupal
        domains:
          - '{{$prefix}}.{{ include "drupal.domain" $ }}'
{{- end }}
---
{{- end }}

{{- else if eq $context_ssl.issuer "selfsigned" }}
apiVersion: {{ include "cert-manager.api-version" . | trim }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls
  duration: 2160h
  renewBefore: 150h 
  commonName: {{ template "drupal.domain" . }}
  dnsNames:
  - {{ template "drupal.domain" . }}
  issuerRef:
    name: {{ $context_ssl.issuer }}
    kind: ClusterIssuer
---

{{- else if eq $context_ssl.issuer "custom" }}
{{- if not $context_ssl.existingTLSSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.ca: {{ $context_ssl.ca | b64enc }}
  tls.crt: {{ $context_ssl.crt | b64enc }}
  tls.key: {{ $context_ssl.key | b64enc }}
---
{{- end }}
{{- end }}

# Certificates for exposeDomains 
{{- range $index, $domain := .Values.exposeDomains }}
{{ $domain := merge $domain $.Values.exposeDomainsDefaults}}
{{- if $domain.ssl }}
{{- if $domain.ssl.enabled }}
{{- if has $domain.ssl.issuer (list "letsencrypt" "letsencrypt-staging") }}
apiVersion: {{ include "cert-manager.api-version" $ | trim }}
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-crt-{{ $index }}
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-override-ingress-name: "{{ $.Release.Name }}-drupal-{{ $domain.ingress }}"
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  secretName: {{ $.Release.Name }}-tls-{{ $index }}
  dnsNames:
  - {{ $domain.hostname }}
  issuerRef:
    name: {{ $domain.ssl.issuer }}
    kind: ClusterIssuer
{{- if eq ( include "cert-manager.api-version" $ | trim ) "certmanager.k8s.io/v1alpha1" }}
  acme:
    config:
      - http01:
          ingress: {{ $.Release.Name }}-drupal-{{ $domain.ingress }}
        domains:
          - {{ $domain.hostname }}
{{- end }}
---

{{- else if eq $domain.ssl.issuer "selfsigned" }}
apiVersion: {{ include "cert-manager.api-version" $ | trim }}
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-crt-{{ $index }}
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  secretName: {{ $.Release.Name }}-tls-{{ $index }}
  duration: 2160h
  renewBefore: 150h 
  commonName: {{ $domain.hostname }}
  dnsNames:
  - {{ $domain.hostname }}
  issuerRef:
    name: {{ $domain.ssl.issuer }}
    kind: ClusterIssuer
---

{{- else if eq $domain.ssl.issuer "custom" }}
{{- if not $domain.ssl.existingTLSSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-tls-{{ $index }}
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $domain.ssl.ca | default "" | b64enc }}
  tls.crt: {{ $domain.ssl.crt | default "" | b64enc }}
  tls.key: {{ $domain.ssl.key | default "" | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
