{{- range $index, $job := .Values.php.cron }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ $index }}
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  backOffLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "drupal.release_labels" $ | nindent 12 }}
        spec:
          containers:
          - name: drupal-cron
            {{- include "drupal.php-container" $ | nindent 12 }}
            volumeMounts:
              {{- include "drupal.volumeMounts" $ | nindent 14 }}
            command: ["/bin/bash", "-c"]
            args:
              - |
                 if [ ! {{ include "drupal.installation-in-progress-test" . }} ]
                 then
                  {{ $job.command | nindent 18 -}}
                 else
                   exit 1
                 fi
            resources:
              {{- $.Values.php.resources | toYaml | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "drupal.volumes" $ | nindent 12 }}

          {{- include "drupal.imagePullSecrets" $ | nindent 10 }}
---
{{- end }}