apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-postinstall"
  labels:
    {{ include "drupal.release_labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postinstall
        {{ include "drupal.php-container" . | indent 8 }}
        command: ["/bin/sh", "-c"]
        args:
        - {{ .Values.php.postinstall.command | quote }}
      {{ include "drupal.imagePullSecrets" . | indent 6 }}
      volumes:
        {{ include "drupal.volumes" . | indent 8 }}
