{{- if .Values.referenceData.enabled }}
{{- if eq .Values.referenceData.referenceEnvironment .Values.environmentName }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-refdata
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.referenceData.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reference-data-cron
            {{- include "drupal.php-container" . | nindent 12 }}
            volumeMounts:
              {{- include "drupal.volumeMounts" . | nindent 14 }}
              - name: reference-data-volume
                mountPath: /app/reference-data
              - name: config
                mountPath: /etc/my.cnf.d/gdpr-dump.cnf
                readOnly: true
                subPath: gdpr-dump
            command: ["/bin/bash", "-c"]
            args:
              - |
                {{ include "drupal.extract-reference-data" . | nindent 16 }}

            resources:
              {{- .Values.php.resources | toYaml | nindent 14 }}
          restartPolicy: Never
          volumes:
            {{- include "drupal.volumes" . | nindent 12 }}
            - name: reference-data-volume
              persistentVolumeClaim:
                claimName: {{ include "drupal.referenceEnvironment" . }}-reference-data

          {{- include "drupal.imagePullSecrets" . | nindent 10 }}
{{- end }}
{{- end }}
---
