{{- if .Values.referenceData.enabled }}
{{- if eq .Values.referenceData.referenceEnvironment .Values.environmentName }}
apiVersion: {{ include "drupal.cron.api-version" . | trim }}
kind: CronJob
metadata:
  name: {{ .Release.Name }}-refdata
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  {{- if .Values.timezone }}
  {{- if eq ( include "drupal.cron.timezone-support" . ) "true" }}
  timeZone: {{ .Values.timezone | quote }}
  {{- end }}
  {{- end }}
  schedule: {{ .Values.referenceData.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 0
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          containers:
          - name: reference-data-cron
            {{- include "drupal.php-container" . | nindent 12 }}
            volumeMounts:
              {{- include "drupal.volumeMounts" . | nindent 14 }}
              - name: reference-data-volume
                mountPath: /app/reference-data
            command: ["/bin/bash", "-c"]
            args:
              - |
                {{ include "drupal.extract-reference-data" . | nindent 16 }}

            resources:
              {{- .Values.referenceData.resources | toYaml | nindent 14 }}
          restartPolicy: Never
          volumes:
            {{- include "drupal.volumes" . | nindent 12 }}
            - name: reference-data-volume
              persistentVolumeClaim:
                claimName: {{ include "drupal.referenceEnvironment" . }}-reference-data

          {{- include "drupal.imagePullSecrets" . | nindent 10 }}
{{- end }}
{{- end }}
---
