{{- if .Values.shell.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-shell
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
type: Opaque
data:
  keyserver.username: {{ ((.Values.shell.gitAuth).keyserver).username | b64enc | quote }}
  keyserver.password: {{ ((.Values.shell.gitAuth).keyserver).password | b64enc | quote }}
{{- end }}
