{{- if or .Values.mailhog.enabled .Values.smtp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-smtp
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.smtp.password }}
  password: "{{ .Values.smtp.password | b64enc }}"
  {{ else }}
  password: ""
  {{ end }}
{{- end }}
