apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: vmproxy
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8429
  selector:
    app: vmproxy
    release: {{ .Release.Name }}