skip-check:
- CKV_K8S_8   # Liveness Probe Should be Configured
- CKV_K8S_9   # Readiness Probe Should be Configured
- CKV_K8S_15  # Image Pull Policy should be Always
- CKV_K8S_28  # Minimize the admission of containers with the NET_RAW capability
- CKV_K8S_31  # Ensure that the seccomp profile is set to docker/default or runtime/default
- CKV_K8S_37  # Minimize the admission of containers with capabilities assigned
- CKV_K8S_40  # Containers should run as a high UID to avoid host conflict
- CKV_K8S_43  # Image should use digest
- CKV_K8S_21  # The default namespace should not be used
