{{- if and ( eq .Capabilities.KubeVersion.Major "1") ( le .Capabilities.KubeVersion.Minor "18" ) }}
{{- if .Values.defaultParams }}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.params }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
