{{- if and ( eq .Capabilities.KubeVersion.Major "1") ( ge $.Capabilities.KubeVersion.Minor "19" ) }}
# This should be deregistered once the controller stops
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi-rclone
spec:
  attachRequired: true
  podInfoOnMount: false
{{- end }}
