{{- if and ( eq .Capabilities.KubeVersion.Major "1") ( ge $.Capabilities.KubeVersion.Minor "20" ) }}
{{- if .Values.defaultParams }}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.params }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
