{{- if and ( eq .Capabilities.KubeVersion.Major "1") ( ge $.Capabilities.KubeVersion.Minor "20" ) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ default "rclone" .Values.storageClass.name }}
  namespace: {{ .Release.Namespace }}
provisioner: csi-rclone
parameters:
  {{- if .Values.storageClass.pathPattern }}
  pathPattern: {{ .Values.storageClass.pathPattern }}
  {{- end }}
{{- end }}
