{{- range $index, $mount := .Values.mounts }}
{{- if $mount.enabled }}
{{- if and (not (hasKey $mount "configMapName")) (not (hasKey $mount "secretName")) -}}
{{- if eq $mount.storageClassName "silta-shared" }}
{{- if eq ( include "silta-cluster.rclone.has-provisioner" $ ) "false" }}
# Mount-enabled: {{ $mount.enabled  }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-{{ $index }}
  labels:
    name: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-{{ $index }}
spec:
  accessModes:
    - {{ $mount.accessModes | default "ReadWriteMany" }}
  capacity:
    storage: {{ $mount.storage }}
  storageClassName: {{ $mount.storageClassName }}
  {{- if $mount.csiDriverName }}
  csi:
    driver: {{ $mount.csiDriverName }}
    volumeHandle: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-{{ $index }}
    volumeAttributes:
      remotePathSuffix: /{{ $.Release.Namespace }}/{{ $.Values.environmentName }}/{{ $index }}
  {{- end }}
---
{{- end }}
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if and ( eq $mount.storageClassName "silta-shared" ) ( eq ( include "silta-cluster.rclone.has-provisioner" $ ) "true" ) }}
  name: {{ $.Release.Name }}-{{ $index }}2
  {{- else }}
  name: {{ $.Release.Name }}-{{ $index }}
  {{- end }}
  labels:
    {{- include "frontend.release_labels" $ | nindent 4 }}
  annotations:
    storage.silta/storage-path: {{ $.Values.environmentName | default $.Release.Name }}/{{ $index }}
spec:
  storageClassName: {{ $mount.storageClassName }}
  accessModes:
    - {{ $mount.accessModes | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ $mount.storage }}
{{- if eq $mount.storageClassName "silta-shared" }}
{{- if eq ( include "silta-cluster.rclone.has-provisioner" $ ) "false" }}
  selector:
    matchLabels:
      name: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-{{ $index }}
{{- end }}
{{- end }}
---
{{- end -}}
{{- end }}
{{- end }}

{{- if $.Values.shell.enabled }}
{{- if eq $.Values.shell.mount.storageClassName "silta-shared" }}
{{- if eq ( include "silta-cluster.rclone.has-provisioner" $ ) "false" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-shell-keys
  labels:
    name: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-shell-keys
spec:
  accessModes:
    - {{ $.Values.shell.mount.accessModes | default "ReadWriteMany" }}
  capacity:
    storage: 50M
  storageClassName: {{ $.Values.shell.mount.storageClassName }}
  {{- if $.Values.shell.mount.csiDriverName }}
  csi:
    driver: {{ $.Values.shell.mount.csiDriverName }}
    volumeHandle: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-shell-keys
    volumeAttributes:
      remotePathSuffix: /{{ $.Release.Namespace }}/{{ $.Values.environmentName }}/shell-keys
      umask: "077"
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if and ( eq $.Values.shell.mount.storageClassName "silta-shared" ) ( eq ( include "silta-cluster.rclone.has-provisioner" $ ) "true" ) }}
  name: {{ $.Release.Name }}-shell-keys2
  {{- else }}
  name: {{ $.Release.Name }}-shell-keys
  {{- end }}
  labels:
    {{- include "frontend.release_labels" $ | nindent 4 }}
  annotations:
    storage.silta/storage-path: {{ $.Values.environmentName | default $.Release.Name }}/shell-keys
    csi-rclone/umask: "077"
spec:
  storageClassName: {{ $.Values.shell.mount.storageClassName }}
  accessModes:
    - {{ $.Values.shell.mount.accessModes | default "ReadWriteMany" }}
  resources:
    requests:
      storage: 50M
{{- if eq $.Values.shell.mount.storageClassName "silta-shared" }}
{{- if eq ( include "silta-cluster.rclone.has-provisioner" $ ) "false" }}
  selector:
    matchLabels:
      name: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-shell-keys
{{- end }}
{{- end }}
---
{{- end }}
