{{- $context_ingress := .Values.ingress.default }}
{{- $context_ssl := .Values.ssl }}
{{- if $context_ingress.tls }}
{{- if eq $context_ssl.issuer "custom" }}
{{- if not $context_ssl.existingTLSSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-custom
  labels:
    {{- include "simple.release_labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.ca: {{ $context_ssl.ca | b64enc }}
  tls.crt: {{ $context_ssl.crt | b64enc }}
  tls.key: {{ $context_ssl.key | b64enc }}
---
{{- end }}
{{- else }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
  {{- if has $context_ssl.issuer (list "letsencrypt" "letsencrypt-staging") }}
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-override-ingress-name: "{{ .Release.Name }}-simple"
  {{- end }}
  labels:
    {{- include "simple.release_labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls
  {{- if eq $context_ssl.issuer "selfsigned" }}
  duration: 2160h
  renewBefore: 150h
  commonName: {{ template "simple.domain" . }}
  {{- end }}
  dnsNames:
  - {{ template "simple.domain" . }}
  issuerRef:
    name: {{ $context_ssl.issuer }}
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: "Always"
---
{{- end }}
{{- end }}

# Certificates for exposeDomains

{{- range $index, $domain := .Values.exposeDomains }}
{{- $domain := mergeOverwrite ($.Values.exposeDomainsDefaults | toYaml | fromYaml) $domain }}
{{- if $domain.ssl }}
{{- if $domain.ssl.enabled }}
{{- if eq $domain.ssl.issuer "custom" }}
{{- if not $domain.ssl.existingTLSSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-tls-{{ $index }}-custom
  labels:
    {{- include "simple.release_labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if $domain.ssl.ca }}
  ca.crt: {{ $domain.ssl.ca | default "" | b64enc }}
  {{- end }}
  tls.crt: {{ $domain.ssl.crt | default "" | b64enc }}
  tls.key: {{ $domain.ssl.key | default "" | b64enc }}
---
{{- end }}
{{- else }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-crt-{{ $index }}
  {{- if has $domain.ssl.issuer (list "letsencrypt" "letsencrypt-staging") }}
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-override-ingress-name: "{{ $.Release.Name }}-simple-{{ $domain.ingress }}"
  {{- end }}
  labels:
    {{- include "simple.release_labels" $ | nindent 4 }}
spec:
  secretName: {{ $.Release.Name }}-tls-{{ $index }}
  {{- if eq $domain.ssl.issuer "selfsigned" }}
  duration: 2160h
  renewBefore: 150h
  commonName: {{ $domain.hostname }}
  {{- end }}
  dnsNames:
  - {{ $domain.hostname }}
  issuerRef:
    name: {{ $domain.ssl.issuer }}
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: "Always"
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
