{{- if .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    {{- include "simple.release_labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret }}
{{- end }} 